### ISSUE TITLE
CORS Issues With API

### ISSUE THREAD

**Issue by carpepraedam** [unh-webappdev/FlashCourses_api#22]
### Description

when making a get request from web app to http://159.65.236.42/flashcards/api/card/list

localhost/:1 XMLHttpRequest cannot load http://159.65.236.42/flashcards/api/card/list/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
webpack-internal:///./node_modules/@angular/core/esm5/core.js:1664 ERROR Response
defaultErrorLogger @ webpack-internal:///./node_modules/@angular/core/esm5/core.js:1664
[Violation] Long running JavaScript task took 440ms

### Steps to Reproduce

1. curl http://159.65.236.42/flashcards/api/card/list/?format=json
2. This works
3. Now create a fetch request from a javascript script. You will see the error above

Expected behavior: Server to respond with json corresponding to specific API endpoint

Actual behavior: CORS issue

Frequency: 100% from scripts that are not hosted on  http://159.65.236.42 (i.e. cross-origin, they don't live on the same domain)

### Steps To Consider

1. Review DRF documentation: http://www.django-rest-framework.org/topics/ajax-csrf-cors/
2. Install django-cors-headers: https://github.com/ottoyiu/django-cors-headers/
3. Adjust common.py to include settings needed for the above package

**Comment by mce123** [comment]
Should be resolved with the recent pull request, by importing api_settings.py into common.py

**Comment by carpepraedam** [comment]
Still getting CORS issues:

fetch('http://159.65.236.42/flashcards/api/deck/list/').then(function(response){ console.log(response.json()) } )

Failed to load http://159.65.236.42/flashcards/api/deck/list/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Suggested Fix

Check django-cors-headers documentation regarding middleware here: https://pypi.python.org/pypi/django-cors-headers/2.0.0

Looks like the middleware settings are missing from common. API team can update these settings

**Comment by mce123** [comment]
This is because Server team didn't implement all of our changes. There's a change to common.py that needs to be made in order for django-cors-headers to work correctly, in INSTALLED_APPS. Also it won't work if api_settings.py isn't imported. It appears to just be the INSTALLED_APPS issue.

Should be installed as such:
INSTALLED_APPS = (
    ...
    'corsheaders',
    ...
)

We couldn't upload our changes to common.py, which is primarily why this issue occurred...

**Comment by mce123** [comment]
Also MIDDLEWARE needs to be updated...

MIDDLEWARE = [ 
    ...
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    ...
]

**Comment by mce123** [comment]
This should be resolved once my pull request is merged and server is updated.

**Comment by carpepraedam** [comment]
Closing. Fixed in PR #34
